### ISSUE TITLE
Gerber file

### ISSUE THREAD

**Issue by Turbox35** [tspopp/AquaMQTT#16]
Hello, is it possible to provide the gerber file as some PCB suppliers support this format and not kicad?

**Comment by tspopp** [comment]
Hey @Turbox35,

i am not familiar with the gerber format. You might want to install [KiCad](https://www.kicad.org/) (it's free!) and export the PCB to the gerber format. I did some quick googling and found a tutorial [here](https://www.pcbway.com/helpcenter/technical_support/Generate_Gerber_file_from_Kicad.html). 

If you successfully created and succeeded with that export, I am happy to receive a PR containing the file to share with others with the same issue :)

Cheers!

**Comment by Turbox35** [comment]
Hello @tspopp 
Thanks for the links. I have installed kicad and generated the gerber zip file but as it was new for me I'm not completely sure that was correctly done.
I have ordered PCB with this gerber file, I will let you informed when I will receive it if all is correct and yes, of course, in this case I will share the gerber file.

**Comment by scoudibou** [comment]
Here is mine, tested and approuved 👍 
[plot.zip](https://github.com/tspopp/AquaMQTT/files/15129589/plot.zip)
