### ISSUE TITLE
Bad connection issue (from hacf forum)

### ISSUE THREAD

**Issue by tspopp** [tspopp/AquaMQTT#24]
Hey @jcjames13009 @scoudibou,

I've been following your discussion on the [hacf forum](https://forum.hacf.fr/t/integration-dun-chauffe-eau-atlantic-explorer-en-mqtt/40493/21), but unfortunately I cannot send any replys there (blocked?). That said, to me it looks like the Logic-Level-Converter Board (blue) from jcjames is not soldered correctly: If I am not wrong, I don't see any soldered pins there.

![image](https://github.com/tspopp/AquaMQTT/assets/66408890/9afb447d-6d90-4edf-b645-98922f37dc05)

Of course there are 12 pads, i just highlighted a few, can you check those?

Cheers

**Comment by jcjames13009** [comment]
Hi @tspopp 

Thanks for your message and taking care about my issue

I double checked the 12 pins and converter is soldered properly. But you're right it looks bad from the picture

I measured voltages when converter is installed on the pcb and have the following values. Whatever if Data wire (the white one) is connected or not to the pcb

![Capture d’écran 2024-06-13 à 21 45 01](https://github.com/tspopp/AquaMQTT/assets/91546361/544c33f1-0518-41aa-8948-39ea5231ff5f)

When testing converter on a breadboard I have 3.2v on all LV outputs and 5v on all HV outputs

I'll receive soon a new converter. I'll test it and will keep you posted

Cheers

JC

**Comment by tspopp** [comment]
Hey @jcjames13009,

not sure if your issue is really hardware related. It is unlikely but possible that the Thermor Aeromax Split 2 is using a different serial protocol which AquaMQTT is not able to understand at this point in time. I am very curios what happens if you set the AquaMQTT Board to Listener Mode (Passthrough Jumper connected) and install [AquaDebug](https://github.com/tspopp/AquaMQTT/tree/main/tools/AquaDebug) on the device. Afterwards you are able to record a trace of the raw serial data using the python script next to AquaDebug. Also have a look in the newly created [Troubleshooting](https://github.com/tspopp/AquaMQTT/tree/main//TROUBLESHOOTING.md) section....

Looking forward!

**Comment by jcjames13009** [comment]
Hi @tspopp 

I was also thinking that the AquaMQTT may not be compatible with my water heater and planned to test it in Listener mode

Your essage arrive at the right time and cool if you add AquaDebug feature. I'll do the test maybe this envenig or beginning of next week and will keep you posted

Cheers

JC

**Comment by henrykuijpers** [comment]
@jcjames13009 did anything come out of this?

**Comment by tspopp** [comment]
I'll close this due to inactivity. We will reopen this in case we get feedback or results.
