### ISSUE TITLE
Transistors - TC-BC457A, 100mA, 45V, hFE/90

### ISSUE THREAD

**Issue by henrykuijpers** [tspopp/AquaMQTT#36]
Is it really needed that the transistors match this specification exactly?

Looking to order on AliExpress, as most other parts (like resistors etc), are also widely available there.

I don't find any hFE/90 transistor there. Also, I don't find a TC-BC457A, only a "BC457B". 
100mA & 45V is common, there, though.

**Comment by tspopp** [comment]
Hey, i've ordered [these](https://www.conrad.de/de/p/tru-components-transistor-bjt-diskret-tc-bc547a-to-92-anzahl-kanaele-1-npn-1581825.html) and soldered them myself. The reason why we need this transistors is already explained here: https://github.com/tspopp/AquaMQTT/issues/33. The [USART in One Wire Mode document](https://ww1.microchip.com/downloads/en/AppNotes/USART-in-One-Wire-Mode-ApplicationNote-DS00002658.pdf) just states BC547.
