### ISSUE TITLE
Add MQTT Discovery Mode for Home Assistant configuration?

### ISSUE THREAD

**Issue by NickdeK** [tspopp/AquaMQTT#40]
Last weekend I installed the AquaMQTT but for the life of my I could not get it to create entities in Home Assistant. I presumed it would create them automatically as other MQTT solution did that by default.

Finally I found a French post somewhere that linked to the yaml file needed to configure Home Assistant here: https://github.com/tspopp/AquaMQTT/blob/main/aquamqtt.yaml

It would be nice if the MQTT Discovery Mode was added so that this device really becomes plug and play. I can understand this might be a bit of work, so maybe a link to the yaml file in a readme somewhere with the note that it's needed to configure Home Assistant would be nice as well.

**Comment by tspopp** [comment]
Fully agree, this part is lacking information. Actually my main goal was getting the software on the Arduino done right and I did not expect an increasing user base. With the ongoing cozytouch backend issues and the compatibility to the Atlantic Explorer there are more people trying AquaMQTT than I've ever expected. In the past I pretty much drew a line as soon as the data was given to the MQTT broker. I did spent very little time in creating a configuration files for backends such as homeassistant or iobroker. Actually it was @scoudibou who helped and provided the mentioned configuration file :+1:

I previously did not know about the [Discovery Mode](https://www.home-assistant.io/integrations/mqtt/#mqtt-discovery) from HomeAssistant, but it sounds fun to implement. I might gonna look into this. Thanks for the suggestion :)
